[2022-03-17 03:25:40,169] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: testing_dag.wget 2020-03-02T06:00:00+00:00 [queued]>
[2022-03-17 03:25:40,214] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: testing_dag.wget 2020-03-02T06:00:00+00:00 [queued]>
[2022-03-17 03:25:40,216] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 03:25:40,217] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-03-17 03:25:40,218] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 03:25:40,245] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): wget> on 2020-03-02T06:00:00+00:00
[2022-03-17 03:25:40,251] {standard_task_runner.py:52} INFO - Started process 1291 to run task
[2022-03-17 03:25:40,259] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'testing_dag', 'wget', '2020-03-02T06:00:00+00:00', '--job-id', '34', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/testing_dag.py', '--cfg-path', '/tmp/tmpc0por4c_', '--error-file', '/tmp/tmphz267jzl']
[2022-03-17 03:25:40,265] {standard_task_runner.py:77} INFO - Job 34: Subtask wget
[2022-03-17 03:25:40,370] {logging_mixin.py:104} INFO - Running <TaskInstance: testing_dag.wget 2020-03-02T06:00:00+00:00 [running]> on host 509d5aa4e827
[2022-03-17 03:25:40,488] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=testing_dag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2020-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-03-02T06:00:00+00:00
[2022-03-17 03:25:40,490] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-17 03:25:40,494] {bash.py:158} INFO - Running command: curl -sSL https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2020-03.csv > /opt/airflow/output_2020-03.csv
[2022-03-17 03:25:40,510] {bash.py:169} INFO - Output:
[2022-03-17 03:25:57,883] {bash.py:173} INFO - curl: (18) transfer closed with 274579532 bytes remaining to read
[2022-03-17 03:25:57,904] {bash.py:177} INFO - Command exited with return code 18
[2022-03-17 03:25:57,939] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-03-17 03:25:57,954] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=testing_dag, task_id=wget, execution_date=20200302T060000, start_date=20220317T032540, end_date=20220317T032557
[2022-03-17 03:25:58,008] {local_task_job.py:146} INFO - Task exited with return code 1
