[2022-03-22 22:49:49,995] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fifa_player_dag.download_dataset 2022-03-22T22:49:44.635498+00:00 [queued]>
[2022-03-22 22:49:50,025] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fifa_player_dag.download_dataset 2022-03-22T22:49:44.635498+00:00 [queued]>
[2022-03-22 22:49:50,027] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-22 22:49:50,028] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-03-22 22:49:50,029] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-22 22:49:50,062] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): download_dataset> on 2022-03-22T22:49:44.635498+00:00
[2022-03-22 22:49:50,072] {standard_task_runner.py:52} INFO - Started process 9975 to run task
[2022-03-22 22:49:50,082] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'fifa_player_dag', 'download_dataset', '2022-03-22T22:49:44.635498+00:00', '--job-id', '122', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/311_download_ingest_gcs.py', '--cfg-path', '/tmp/tmpkcnbqoly', '--error-file', '/tmp/tmpod5xh12w']
[2022-03-22 22:49:50,090] {standard_task_runner.py:77} INFO - Job 122: Subtask download_dataset
[2022-03-22 22:49:50,172] {logging_mixin.py:104} INFO - Running <TaskInstance: fifa_player_dag.download_dataset 2022-03-22T22:49:44.635498+00:00 [running]> on host 5b89a1c58760
[2022-03-22 22:49:50,257] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fifa_player_dag
AIRFLOW_CTX_TASK_ID=download_dataset
AIRFLOW_CTX_EXECUTION_DATE=2022-03-22T22:49:44.635498+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-22T22:49:44.635498+00:00
[2022-03-22 22:49:50,264] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-22 22:49:50,268] {bash.py:158} INFO - Running command: kaggle datasets download -p /opt/airflow stefanoleone992/fifa-22-complete-player-dataset && unzip /opt/airflow/*.zip -d /opt/airflow
[2022-03-22 22:49:50,288] {bash.py:169} INFO - Output:
[2022-03-22 22:49:52,688] {bash.py:173} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/airflow/.kaggle/kaggle.json'
[2022-03-22 22:49:52,691] {bash.py:173} INFO - fifa-22-complete-player-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)
[2022-03-22 22:49:52,880] {bash.py:173} INFO - Archive:  /opt/airflow/fifa-22-complete-player-dataset.zip
[2022-03-22 22:49:52,885] {bash.py:173} INFO - replace /opt/airflow/Career Mode female player datasets - FIFA 16-22.xlsx? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
[2022-03-22 22:49:52,887] {bash.py:173} INFO - (EOF or read error, treating as "[N]one" ...)
[2022-03-22 22:49:52,889] {bash.py:177} INFO - Command exited with return code 1
[2022-03-22 22:49:52,921] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-03-22 22:49:52,931] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=fifa_player_dag, task_id=download_dataset, execution_date=20220322T224944, start_date=20220322T224950, end_date=20220322T224952
[2022-03-22 22:49:53,006] {local_task_job.py:146} INFO - Task exited with return code 1
